databases:
  - name: prodev_db
    databaseName: ecommerce
    user: prodev_user
    plan: free

services:
  - type: web
    name: prodev-backend
    env: docker
    dockerContext: .
    dockerfilePath: infra/docker/Dockerfile
    plan: free
    envVars:
      - key: POSTGRES_DB
        fromDatabase:
          name: prodev_db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: prodev_db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: prodev_db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: prodev_db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: prodev_db
          property: port
      - key: REDIS_URL
        fromService:
          type: redis
          name: prodev-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: prodev-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: prodev-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: src.core.settings
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "prodev-backend.onrender.com"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

    dockerCommand: "./scripts/start_render.sh"

  - type: redis
    name: prodev-redis
    plan: free
    ipAllowList: []