apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DEBUG: "True"
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_DB: "ecommerce"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres"  
  POSTGRES_PORT: "5432"
  RABBITMQ_USER: "admin"
  CELERY_BROKER_URL: "amqp://admin:admin@rabbitmq:5672//"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  REDIS_URL: "redis://redis:6379/1"
  DJANGO_SETTINGS_MODULE: "src.core.settings"