apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "django-insecure-change-me-for-production"
  POSTGRES_PASSWORD: "postgres"
  RABBITMQ_PASS: "admin"
  CLOUDINARY_API_KEY: "456947274755713"
  CLOUDINARY_API_SECRET: "8VkXxoMvoxkH7tiGwrdocif9Pe0"
  CLOUDINARY_CLOUD_NAME: "duofhfjqm"
  CLOUDINARY_URL: "cloudinary://456947274755713:8VkXxoMvoxkH7tiGwrdocif9Pe0@duofhfjqm"