services:
  jenkins:
    build: .
    container_name: prodev-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
      - //c/Users/kwame/.kube:/var/jenkins_home/.kube
      
    user: root

volumes:
  jenkins_home: